## Clock Signal
## The input clock signal is connected to pin E3 on the FPGA
## The frequency is set to 100 MHz
set_property -dict { PACKAGE_PIN Y18 IOSTANDARD LVCMOS33 } [get_ports pclk]
set_property -dict { PACKAGE_PIN P4 IOSTANDARD LVCMOS33 } [get_ports reset]

set_property -dict { PACKAGE_PIN W4 IOSTANDARD LVCMOS33 } [get_ports {sw[0]}]
set_property -dict { PACKAGE_PIN R4 IOSTANDARD LVCMOS33 } [get_ports {sw[1]}]
set_property -dict { PACKAGE_PIN T4 IOSTANDARD LVCMOS33 } [get_ports {sw[2]}]
set_property -dict { PACKAGE_PIN T5 IOSTANDARD LVCMOS33 } [get_ports {sw[3]}]
set_property -dict { PACKAGE_PIN U5 IOSTANDARD LVCMOS33 } [get_ports {sw[4]}]
set_property -dict { PACKAGE_PIN W6 IOSTANDARD LVCMOS33 } [get_ports {sw[5]}]
set_property -dict { PACKAGE_PIN W5 IOSTANDARD LVCMOS33 } [get_ports {sw[6]}]
set_property -dict { PACKAGE_PIN U6 IOSTANDARD LVCMOS33 } [get_ports {sw[7]}]
set_property -dict { PACKAGE_PIN V5 IOSTANDARD LVCMOS33 } [get_ports {sw[8]}]
set_property -dict { PACKAGE_PIN R6 IOSTANDARD LVCMOS33 } [get_ports {sw[9]}]
set_property -dict { PACKAGE_PIN T6 IOSTANDARD LVCMOS33 } [get_ports {sw[10]}]
set_property -dict { PACKAGE_PIN Y6 IOSTANDARD LVCMOS33 } [get_ports {sw[11]}]
set_property -dict { PACKAGE_PIN AA6 IOSTANDARD LVCMOS33 } [get_ports {sw[12]}]
set_property -dict { PACKAGE_PIN V7 IOSTANDARD LVCMOS33 } [get_ports {sw[13]}]
set_property -dict { PACKAGE_PIN AB7 IOSTANDARD LVCMOS33 } [get_ports {confirm}]

set_property -dict { PACKAGE_PIN J17 IOSTANDARD LVCMOS33 } [get_ports {leds[0]}]
set_property -dict { PACKAGE_PIN L14 IOSTANDARD LVCMOS33 } [get_ports {leds[1]}]
set_property -dict { PACKAGE_PIN L15 IOSTANDARD LVCMOS33 } [get_ports {leds[2]}]
set_property -dict { PACKAGE_PIN L16 IOSTANDARD LVCMOS33 } [get_ports {leds[3]}]
set_property -dict { PACKAGE_PIN K16 IOSTANDARD LVCMOS33 } [get_ports {leds[4]}]
set_property -dict { PACKAGE_PIN M15 IOSTANDARD LVCMOS33 } [get_ports {leds[5]}]
set_property -dict { PACKAGE_PIN M16 IOSTANDARD LVCMOS33 } [get_ports {leds[6]}]
set_property -dict { PACKAGE_PIN M17 IOSTANDARD LVCMOS33 } [get_ports {leds[7]}]
set_property -dict { PACKAGE_PIN N19 IOSTANDARD LVCMOS33 } [get_ports {leds[8]}]
set_property -dict { PACKAGE_PIN N20 IOSTANDARD LVCMOS33 } [get_ports {leds[9]}]
set_property -dict { PACKAGE_PIN M20 IOSTANDARD LVCMOS33 } [get_ports {leds[10]}]
set_property -dict { PACKAGE_PIN K13 IOSTANDARD LVCMOS33 } [get_ports {leds[11]}]
set_property -dict { PACKAGE_PIN K14 IOSTANDARD LVCMOS33 } [get_ports {leds[12]}]
set_property -dict { PACKAGE_PIN M13 IOSTANDARD LVCMOS33 } [get_ports {leds[13]}]
set_property -dict { PACKAGE_PIN L13 IOSTANDARD LVCMOS33 } [get_ports {leds[14]}]
set_property -dict { PACKAGE_PIN K17 IOSTANDARD LVCMOS33 } [get_ports {leds[15]}]
set_property -dict { PACKAGE_PIN A21 IOSTANDARD LVCMOS33 } [get_ports {signal}]

set_property -dict { PACKAGE_PIN C19 IOSTANDARD LVCMOS33 } [get_ports {seg_enables[0]}]
set_property -dict { PACKAGE_PIN E19 IOSTANDARD LVCMOS33 } [get_ports {seg_enables[1]}]
set_property -dict { PACKAGE_PIN D19 IOSTANDARD LVCMOS33 } [get_ports {seg_enables[2]}]
set_property -dict { PACKAGE_PIN F18 IOSTANDARD LVCMOS33 } [get_ports {seg_enables[3]}]
set_property -dict { PACKAGE_PIN E18 IOSTANDARD LVCMOS33 } [get_ports {seg_enables[4]}]
set_property -dict { PACKAGE_PIN B20 IOSTANDARD LVCMOS33 } [get_ports {seg_enables[5]}]
set_property -dict { PACKAGE_PIN A20 IOSTANDARD LVCMOS33 } [get_ports {seg_enables[6]}]
set_property -dict { PACKAGE_PIN A18 IOSTANDARD LVCMOS33 } [get_ports {seg_enables[7]}]

set_property -dict { PACKAGE_PIN F15 IOSTANDARD LVCMOS33 } [get_ports {segs[0]}]
set_property -dict { PACKAGE_PIN F13 IOSTANDARD LVCMOS33 } [get_ports {segs[1]}]
set_property -dict { PACKAGE_PIN F14 IOSTANDARD LVCMOS33 } [get_ports {segs[2]}]
set_property -dict { PACKAGE_PIN F16 IOSTANDARD LVCMOS33 } [get_ports {segs[3]}]
set_property -dict { PACKAGE_PIN E17 IOSTANDARD LVCMOS33 } [get_ports {segs[4]}]
set_property -dict { PACKAGE_PIN C14 IOSTANDARD LVCMOS33 } [get_ports {segs[5]}]
set_property -dict { PACKAGE_PIN C15 IOSTANDARD LVCMOS33 } [get_ports {segs[6]}]

## VGA Display
set_property PACKAGE_PIN M21 [get_ports hsync]
set_property PACKAGE_PIN L21 [get_ports vsync]
set_property PACKAGE_PIN G17 [get_ports {vga_signal[0]}]
set_property PACKAGE_PIN G18 [get_ports {vga_signal[1]}]
set_property PACKAGE_PIN J15 [get_ports {vga_signal[2]}]
set_property PACKAGE_PIN H15 [get_ports {vga_signal[3]}]
set_property PACKAGE_PIN H17 [get_ports {vga_signal[4]}]
set_property PACKAGE_PIN H18 [get_ports {vga_signal[5]}]
set_property PACKAGE_PIN J22 [get_ports {vga_signal[6]}]
set_property PACKAGE_PIN H22 [get_ports {vga_signal[7]}]
set_property PACKAGE_PIN H20 [get_ports {vga_signal[8]}]
set_property PACKAGE_PIN G20 [get_ports {vga_signal[9]}]
set_property PACKAGE_PIN K21 [get_ports {vga_signal[10]}]
set_property PACKAGE_PIN K22 [get_ports {vga_signal[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports hsync]
set_property IOSTANDARD LVCMOS33 [get_ports vsync]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_signal[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_signal[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_signal[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_signal[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_signal[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_signal[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_signal[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_signal[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_signal[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_signal[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_signal[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_signal[11]}]

# Keyboard
set_property PACKAGE_PIN L5 [get_ports {col_out[0]}]
set_property PACKAGE_PIN J6 [get_ports {col_out[1]}]
set_property PACKAGE_PIN K6 [get_ports {col_out[2]}]
set_property PACKAGE_PIN M2 [get_ports {col_out[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {col_out[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {col_out[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {col_out[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {col_out[3]}]

set_property PACKAGE_PIN K3 [get_ports {row_in[0]}]
set_property PACKAGE_PIN L3 [get_ports {row_in[1]}]
set_property PACKAGE_PIN J4 [get_ports {row_in[2]}]
set_property PACKAGE_PIN K4 [get_ports {row_in[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {row_in[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {row_in[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {row_in[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {row_in[3]}]
